data.push(["Month", "Day", "Day of Month", "League", "Where", "Where", "Time"]);
data.push(["October", "Monday", "2nd", "Ladies 4", "Trident", "Holmewood House", "8"]);
data.push(["October", "Wednesday", "4th", "Mixed C", "Angel", "Angel Centre", "8"]);
data.push(["October", "Wednesday", "4th", "Mixed D", "Angel", "Angel Centre", "8"]);
data.push(["October", "Friday", "6th", "Mixed C", "Angel", "Angel Centre", "8"]);
data.push(["October", "Friday", "6th", "Mixed D", "Angel", "Angel Centre", "8"]);
data.push(["October", "Monday", "9th", "Mixed A", "Sevenoaks A", "Weald of Kent Sevenoaks", "8.15"]);
data.push(["October", "Tuesday", "10th", "Edenbridge Combi", "Tatsfield", "The Village Hall Tatsfield", "8"]);
data.push(["October", "Friday", "13th", "Ladies 6", "AIT", "Angel Centre", "8"]);
data.push(["October", "Friday", "13th", "Mens C", "Langton Green", "Angel Centre", "8"]);
data.push(["October", "Sunday", "15th", "Mens A", "Chelwood Gate", "Michael Hall School", "7.30"]);
data.push(["October", "Monday", "16th", "Ladies 6", "Trident B", "Holmewood House", "8"]);
data.push(["October", "Monday", "16th", "Edenbridge Mens", "Felbridge", "East Grinstead Sports Club", "7.30"]);
data.push(["October", "Wednesday", "18th", "Composite Cups", "Langton Green", "Angel Centre", "8"]);
data.push(["October", "Friday", "20th", "Ladies 4", "Felbridge", "Angel Centre", "8"]);
data.push(["October", "Friday", "20th", "Mens A", "Felbridge", "Angel Centre", "8"]);
data.push(["October", "Friday", "20th", "Mens C", "St Johns E", "Angel Centre", "8"]);
data.push(["October", "Friday", "27th", "Ladies 4", "Wadhurst", "Angel Centre", "8"]);
data.push(["October", "Friday", "27th", "Mens A", "Hildenborough A", "Walthamstow Hall", "8"]);
data.push(["October", "Friday", "27th", "Edenbridge Mens", "St Piers", "Angel Centre", "8"]);
data.push(["November", "Wednesday", "1st", "Composite Cups", "Felbridge", "Angel Centre", "8"]);
data.push(["November", "Thursday", "2nd", "Ladies 4", "Hilden Grange", "Hilden Grange School", "8"]);
data.push(["November", "Friday", "3rd", "Mixed C", "St Johns E", "Tunbridge Wells Sports Centre", "8.30"]);
data.push(["November", "Sunday", "5th", "Mens A", "Trident B", "Holmewood House", "7"]);
data.push(["November", "Wednesday", "8th", "Edenbridge Cups", "Newick", "Angel Centre", "8"]);
data.push(["November", "Friday", "10th", "Ladies 6", "St Johns B", "Tunbridge Wells Sports Centre", "7.30"]);
data.push(["November", "Friday", "10th", "Masters", "Langton Green", "Village Hall Langton Green", "7.30"]);
data.push(["November", "Friday", "10th", "Mens A", "Hildenborough A", "Angel Centre", "8"]);
data.push(["November", "Friday", "10th", "Mens C", "Sevenoaks C", "Angel Centre", "8"]);
data.push(["November", "Monday", "13th", "Mixed B", "Sevenoaks C", "Weald of Kent Sevenoaks", "8.15"]);
data.push(["November", "Monday", "13th", "Mixed D", "Hilden Grange B", "Hilden Grange School", "8"]);
data.push(["November", "Wednesday", "15th", "Edenbridge Cups", "Newick", "Newick Village Hall", "8.15"]);
data.push(["November", "Thursday", "16th", "Ladies 4", "AIT", "Mascalls School", "8.05"]);
data.push(["November", "Friday", "17th", "Mens B", "St Johns C", "Tunbridge Wells Sports Centre", "7.30"]);
data.push(["November", "Wednesday", "22nd", "Ladies 6", "Trident B", "Angel Centre", "8"]);
data.push(["November", "Wednesday", "22nd", "Mixed C", "Hilden Grange B", "Hilden Grange School", "8"]);
data.push(["November", "Friday", "24th", "Ladies 4", "Langton Green", "Angel Centre", "8"]);
data.push(["November", "Friday", "24th", "Mens B", "St Johns B", "Angel Centre", "8"]);
data.push(["November", "Tuesday", "28th", "Mixed B", "Hilden Grange A", "Hilden Grange School", "8"]);
data.push(["November", "Thursday", "30th", "Masters", "Wadhurst B", "Commemoration Hall, Wadhurst", "7.30"]);
data.push(["December", "Friday", "1st", "Ladies 4", "Hilden Grange", "Angel Centre", "8"]);
data.push(["December", "Friday", "1st", "Mens B", "Sevenoaks B", "Angel Centre", "8"]);
data.push(["December", "Monday", "4th", "Masters", "Trident", "Holmewood House", "8"]);
data.push(["December", "Monday", "4th", "Mixed A", "Trident C", "Holmewood House", "8"]);
data.push(["December", "Wednesday", "6th", "Mens A", "Felbridge", "East Grinstead Sports Club", "7.30"]);
data.push(["December", "Thursday", "7th", "Ladies 6", "AIT", "Mascalls School", "8.05"]);
data.push(["December", "Friday", "8th", "Mixed B", "Hilden Grange A", "Angel Centre", "8"]);
data.push(["December", "Friday", "8th", "Mixed D", "Hilden Grange B", "Angel Centre", "8"]);
data.push(["December", "Wednesday", "13th", "Ladies 4", "Felbridge", "East Grinstead Sports Club", "7.30"]);
data.push(["December", "Thursday", "14th", "Mixed C", "Wadhurst", "Commemoration Hall, Wadhurst", "7"]);
data.push(["December", "Friday", "15th", "Mixed B", "St Johns C", "Angel Centre", "8"]);
data.push(["December", "Friday", "15th", "Mixed D", "St Johns D", "Angel Centre", "8"]);
data.push(["December", "Thursday", "21st", "Masters", "Wadhurst A", "Commemoration Hall, Wadhurst", "7.30"]);
data.push(["January", "Friday", "5th", "Ladies 4", "AIT", "Angel Centre", "8"]);
data.push(["January", "Friday", "5th", "Mens B", "St Johns B", "Tunbridge Wells Sports Centre", "7.30"]);
data.push(["January", "Sunday", "7th", "Mixed B", "Trident E", "Holmewood House", "8"]);
data.push(["January", "Monday", "8th", "Masters", "Hilden Grange", "Hilden Grange School", "8"]);
data.push(["January", "Wednesday", "10th", "Mixed C", "Wadhurst", "Angel Centre", "8"]);
data.push(["January", "Friday", "12th", "Masters", "Sevenoaks", "Angel Centre", "8"]);
data.push(["January", "Friday", "12th", "Mixed A", "Hildenborough B", "Angel Centre", "8"]);
data.push(["January", "Friday", "12th", "Mixed D", "Langton Green", "Village Hall Langton Green", "7.30"]);
data.push(["January", "Monday", "15th", "Mens A", "AIT A", "Mascalls School", "8.05"]);
data.push(["January", "Wednesday", "17th", "Mixed C", "St Johns E", "Angel Centre", "8"]);
data.push(["January", "Friday", "19th", "Mixed B", "Sevenoaks C", "Angel Centre", "8"]);
data.push(["January", "Friday", "19th", "Mixed D", "St Johns E", "Angel Centre", "8"]);
data.push(["January", "Wednesday", "24th", "Mens A", "Trident A", "Angel Centre", "8"]);
data.push(["January", "Thursday", "25th", "Mens B", "Hildenborough D", "Walthamstow Hall", "8"]);
data.push(["January", "Friday", "26th", "Mixed A", "St Johns A", "Tunbridge Wells Sports Centre", "7.30"]);
data.push(["January", "Friday", "26th", "Edenbridge Combi", "Imberwood", "Brambletye School", "8.15"]);
data.push(["January", "Friday", "26th", "Edenbridge Mens", "Felbridge", "Angel Centre", "8"]);
data.push(["January", "Monday", "29th", "Mens C", "Sevenoaks C", "Weald of Kent Sevenoaks", "8.15"]);
data.push(["January", "Wednesday", "31st", "Masters", "Wadhurst A", "Angel Centre", "8"]);
data.push(["February", "Friday", "2nd", "Mixed A", "Hildenborough B", "Walthamstow Hall", "8"]);
data.push(["February", "Wednesday", "7th", "Mixed B", "Trident E", "Angel Centre", "8"]);
data.push(["February", "Thursday", "8th", "Mixed D", "Wadhurst", "Commemoration Hall, Wadhurst", "7"]);
data.push(["February", "Friday", "9th", "Masters", "Hilden Grange", "Angel Centre", "8"]);
data.push(["February", "Friday", "9th", "Mens C", "Langton Green", "Village Hall Langton Green", "7.30"]);
data.push(["February", "Friday", "16th", "Mixed B", "Hildenborough E", "Walthamstow Hall", "8"]);
data.push(["February", "Friday", "16th", "Edenbridge Mens", "St Piers", "St Piers Sports Hall", "8"]);
data.push(["February", "Wednesday", "21st", "Edenbridge Combi", "Angels vs Newick", "Angel Centre", "8"]);
data.push(["February", "Friday", "23rd", "Ladies 4", "Trident", "Angel Centre", "8"]);
data.push(["February", "Friday", "23rd", "Mens B", "Hilden Grange", "Angel Centre", "8"]);
data.push(["February", "Wednesday", "28th", "Mixed D", "Langton Green", "Angel Centre", "8"]);
data.push(["March", "Thursday", "1st", "Mixed A", "AIT B", "Mascalls School", "8.15"]);
data.push(["March", "Friday", "2nd", "Mixed B", "Hildenborough E", "Angel Centre", "8"]);
data.push(["March", "Friday", "2nd", "Mixed D", "Wadhurst", "Angel Centre", "8"]);
data.push(["March", "Wednesday", "7th", "Mixed C", "Langton Green", "Angel Centre", "8"]);
data.push(["March", "Friday", "9th", "Mens A", "Chelwood Gate", "Angel Centre", "8"]);
data.push(["March", "Friday", "9th", "Mens C", "St Johns D", "Angel Centre", "8"]);
data.push(["March", "Friday", "9th", "Edenbridge Combi", "Tatsfield", "Angel Centre", "8"]);
data.push(["March", "Monday", "12th", "Edenbridge Combi", "Felbridge", "East Grinstead Sports Club", "7.30"]);
data.push(["March", "Wednesday", "14th", "Masters", "Trident", "Angel Centre", "8"]);
data.push(["March", "Friday", "16th", "Ladies 6", "St Johns B", "Angel Centre", "8"]);
data.push(["March", "Friday", "16th", "Mixed C", "Hilden Grange B", "Angel Centre", "8"]);
data.push(["March", "Sunday", "18th", "Mens A", "Trident A", "Holmewood House", "8"]);
data.push(["March", "Tuesday", "20th", "Mixed C", "Langton Green", "Village Hall Langton Green", "7.30"]);
data.push(["March", "Friday", "23rd", "Ladies 6", "St Johns C", "Angel Centre", "8"]);
data.push(["March", "Friday", "23rd", "Mens B", "Hildenborough D", "Angel Centre", "8"]);
data.push(["March", "Friday", "23rd", "Mixed D", "St Johns E", "Tunbridge Wells Sports Centre", "8.30"]);
data.push(["March", "Wednesday", "28th", "Masters", "Langton Green", "Angel Centre", "8"]);
data.push(["March", "Thursday", "29th", "Ladies 4", "Wadhurst", "Commemoration Hall, Wadhurst", "7.30"]);
data.push(["April", "Wednesday", "4th", "Mens A", "Trident B", "Angel Centre", "8"]);
data.push(["April", "Wednesday", "4th", "Edenbridge Combi", "Newick", "Newick Village Hall", "8.15"]);
data.push(["April", "Friday", "6th", "Mixed A", "Sevenoaks A", "Angel Centre", "8"]);
data.push(["April", "Friday", "6th", "Mixed C", "St Johns D", "Tunbridge Wells Sports Centre", "7.30"]);
data.push(["April", "Friday", "13th", "Mens A", "AIT A", "Angel Centre", "8"]);
data.push(["April", "Friday", "13th", "Mens C", "St Johns D", "Tunbridge Wells Sports Centre", "8.30"]);
data.push(["April", "Friday", "13th", "Edenbridge Combi", "Felbridge", "Angel Centre", "8"]);
data.push(["April", "Monday", "16th", "Masters", "Sevenoaks", "Weald of Kent Sevenoaks", "8.15"]);
data.push(["April", "Tuesday", "17th", "Mens B", "Hilden Grange", "Hilden Grange School", "8"]);
data.push(["April", "Wednesday", "18th", "Mixed A", "Trident C", "Angel Centre", "8"]);
data.push(["April", "Friday", "20th", "Ladies 4", "Langton Green", "Village Hall Langton Green", "7.30"]);
data.push(["April", "Friday", "20th", "Mens C", "St Johns E", "Tunbridge Wells Sports Centre", "8.30"]);
data.push(["April", "Friday", "20th", "Edenbridge Mens", "Imberwood", "Brambletye School", "8.15"]);
data.push(["April", "Wednesday", "25th", "Masters", "Wadhurst B", "Angel Centre", "8"]);
data.push(["April", "Friday", "27th", "Ladies 6", "St Johns C", "Tunbridge Wells Sports Centre", "7.30"]);
data.push(["April", "Friday", "27th", "Mens B", "St Johns C", "Angel Centre", "8"]);
data.push(["April", "Friday", "27th", "Mixed D", "St Johns D", "Tunbridge Wells Sports Centre", "7.30"]);
data.push(["May", "Wednesday", "2nd", "Edenbridge Combi", "St Piers", "Angel Centre", "8"]);
data.push(["May", "Friday", "4th", "Mixed A", "St Johns A", "Angel Centre", "8"]);
data.push(["May", "Friday", "4th", "Mixed B", "St Johns C", "Tunbridge Wells Sports Centre", "7.30"]);
data.push(["May", "Friday", "11th", "Mixed A", "AIT B", "Angel Centre", "8"]);
data.push(["May", "Friday", "11th", "Mixed C", "St Johns D", "Angel Centre", "8"]);
data.push(["May", "Friday", "18th", "Edenbridge Combi", "Imberwood", "Angel Centre", "8"]);
data.push(["May", "Friday", "18th", "Edenbridge Mens", "Imberwood", "Angel Centre", "8"]);
data.push(["May", "Friday", "25th", "Edenbridge Combi", "St Piers", "St Piers Sports Hall", "8"]);