data.push(["Month", "Day", "Day of Month", "League", "Where", "Where", "Time"]);
data.push(["September", "Friday", "30th", "Geoff Brown Cup", "St Piers", "St Piers Sports Hall", "8"]);
data.push(["October", "Monday", "3rd", "Mixed C", "Sevenoaks", "Sackville School", "8.15"]);
data.push(["October", "Friday", "7th", "Mixed D", "Sevenoaks C", "Angel Centre", "8"]);
data.push(["October", "Friday", "7th", "Ladies A", "Trident B", "Angel Centre", "8"]);
data.push(["October", "Friday", "7th", "Mens A", "St Johns A", "Angel Centre", "8"]);
data.push(["October", "Wednesday", "12th", "Masters", "St Gregs", "Angel Centre", "8"]);
data.push(["October", "Friday", "14th", "Mens C", "Langton Green", "Langton Green", "7.3"]);
data.push(["October", "Friday", "14th", "Peter Welch cup", "Felbridge", "Angel Centre", "8"]);
data.push(["October", "Friday", "14th", "Mens A", "St Gregs", "Angel Centre", "8"]);
data.push(["October", "Tuesday", "18th", "Mixed A", "Sevenoaks A", "Sackville School", "8.15"]);
data.push(["October", "Wednesday", "19th", "Edenbridge Comb", "Imberwood", "Angel Centre", "8"]);
data.push(["October", "Friday", "21st", "Mixed A", "St Johns A", "Angel Centre", "8"]);
data.push(["October", "Friday", "21st", "Mixed D", "St Johns D", "Angel Centre", "8"]);
data.push(["October", "Friday", "21st", "Masters", "St Gregs", "Putlands", "7.3"]);
data.push(["October", "Wednesday", "26th", "Edenbridge Comb", "Newick", "Angel Centre", "8"]);
data.push(["October", "Friday", "28th", "Ladies 4", "Hilden Grange", "Angel Centre", "8"]);
data.push(["October", "Friday", "28th", "Mixed A", "St Johns", "St Johns Sports Centre", "7.3"]);
data.push(["October", "Friday", "28th", "Mens B", "Chelwood Gate", "Angel Centre", "8"]);
data.push(["November", "Wednesday", "2nd", "Mens C", "St Johns C", "Angel Centre", "8"]);
data.push(["November", "Friday", "4th", "Mens A", "Hildenborough B", "Angel Centre", "8"]);
data.push(["November", "Friday", "4th", "Ladies 4", "Trident", "Angel Centre", "8"]);
data.push(["November", "Friday", "4th", "Mens C", "St Johns D", "Angel Centre", "8"]);
data.push(["November", "Monday", "7th", "Edenbridge Mens", "Felbridge", "East Grinstead Sports Club", "7.3"]);
data.push(["November", "Monday", "7th", "Composite A Cup", "Trident", "Holmewood House School", "8"]);
data.push(["November", "Wednesday", "9th", "Mixed C", "St Johns C", "Angel Centre", "8"]);
data.push(["November", "Friday", "11th", "Mixed B", "Hildenborough C", "Angel Centre", "8"]);
data.push(["November", "Friday", "11th", "Composite B", "Hilden Grange", "Angel Centre", "8"]);
data.push(["November", "Monday", "14th", "Mens A", "Trident C", "Holmewood House School", "8"]);
data.push(["November", "Thursday", "17", "Mixed D", "Wadhurst", "Wadhurst Village hall", "7"]);
data.push(["November", "Friday", "18th", "Ladies A", "Hildenborough B", "Walthamstow Hall School", "7.45"]);
data.push(["November", "Friday", "18th", "Mens B", "St Johns B", "St Johns Sports Centre", "7.3"]);
data.push(["November", "Friday", "25th", "Mens B", "Hildenborough D", "Angel Centre", "8"]);
data.push(["November", "Friday", "25th", "Mixed D", "Hilden Grange B", "Angel Centre", "8"]);
data.push(["November", "Monday", "28th", "Mens A", "AIT C", "Mascalls School", "8.15"]);
data.push(["November", "Wednesday", "30th", "Mens B", "Sevenoaks B", "Angel Centre", "8"]);
data.push(["December", "Friday", "2nd", "Mens A", "Hildenborough C", "Angel Centre", "8"]);
data.push(["December", "Friday", "2nd", "Mixed C", "Trident F", "Angel Centre", "8"]);
data.push(["December", "Friday", "2nd", "Mens C", "St Johns D", "St Johns Sports Centre", "7.3"]);
data.push(["December", "Tuesday", "6th", "Ladies 4", "Hilden Grange", "Hilden Grange School", "8"]);
data.push(["December", "Wednesday", "7th", "Masters", "Wadhurst B", "Angel Centre", "8"]);
data.push(["December", "Friday", "9th", "Mixed A", "Hildenborough B", "Walthamstow Hall School", "7.45"]);
data.push(["December", "Friday", "9th", "Mixed C", "St Johns B", "Angel Centre", "8.3"]);
data.push(["December", "Monday", "12th", "Mens B", "Sevenoaks A", "Sackville School", "8.15"]);
data.push(["January", "Thursday", "5th", "Mens B", "Hildenborough D", "Walthamstow Hall School", "7.45"]);
data.push(["January", "Friday", "6th", "Ladies 4", "Langton Green", "Angel Centre", "8"]);
data.push(["January", "Friday", "6th", "Mixed A", "Sevenoaks A", "Angel Centre", "8"]);
data.push(["January", "Friday", "6th", "Mixed C", "St Johns B", "St Johns Sports Centre", "8"]);
data.push(["January", "Wednesday", "11th", "Edenbridge Comb", "Newick", "Newick Village Hall", "8.15"]);
data.push(["January", "Friday", "13th", "Mixed B", "Hildenborough D", "Walthamstow Hall School", "7.45"]);
data.push(["January", "Friday", "13th", "Mens C", "Sevenoaks C", "Angel Centre", "8"]);
data.push(["January", "Sunday", "15th", "Ladies A", "Trident B", "Holmewood House School", "8"]);
data.push(["January", "Wednesday", "18th", "Mixed B", "AIT C", "Angel Centre", "8"]);
data.push(["January", "Friday", "20th", "Masters", "Langton Green", "Langton Green Village Hall", "7.3"]);
data.push(["January", "Friday", "20th", "Ladies A", "St Johns A", "Angel Centre", "8"]);
data.push(["January", "Friday", "20th", "Mixed D", "St Johns D", "St Johns Sports Centre", "7.3"]);
data.push(["January", "Monday", "23rd", "Masters", "Sevenoaks", "Sackville", "8.15"]);
data.push(["January", "Friday", "27th", "Mixed C", "Hildenborough E", "Angel Centre", "8"]);
data.push(["January", "Friday", "27th", "Mens C", "St Johns C", "St Johns Sports Centre", "7.3"]);
data.push(["January", "Friday", "27th", "Mixed A", "AIT A", "Angel Centre", "8"]);
data.push(["January", "Monday", "30th", "Ladies 4", "St Johns", "TOGS", "7.3"]);
data.push(["February", "Wednesday", "1st", "Mixed B", "Trident D", "Angel Centre", "8"]);
data.push(["February", "Friday", "3rd", "Mens A", "Hildenborough B", "Walthamstow Hall School", "7.45"]);
data.push(["February", "Friday", "3rd", "Masters", "Wadhurst A", "Angel Centre", "8"]);
data.push(["February", "Friday", "3d", "Edenbridge Mens", "Imberwood", "Angel Centre", ""]);
data.push(["February", "Monday", "6th", "Mixed B", "AIT C", "Mascalls", "8.15"]);
data.push(["February", "Thursday", "9th", "Ladies 4", "Wadhurst", "Wadhurst Village Hall", "7.3"]);
data.push(["February", "Friday", "10th", "Ladies A", "St Johns B", "St Johns Sports Centre", "7.3"]);
data.push(["February", "Friday", "10th", "Edenbridge Comb", "Imberwood", "Brambletye School", "8.15"]);
data.push(["February", "Wednesday", "15th", "Mens B", "Sevenoaks A", "Angel Centre", "8"]);
data.push(["February", "Friday", "17th", "Ladies 4", "Wadhurst", "Angel Centre", "8"]);
data.push(["February", "Friday", "17th", "Mens C", "Hilden Grange", "Hilden Grange School", "8"]);
data.push(["February", "Friday", "17th", "Mens A", "St Gregs", "Putlands", "7.3"]);
data.push(["February", "Monday", "20th", "Ladies 4", "AIT 4", "Mascalls School", "8.15"]);
data.push(["February", "Thursday", "23rd", "Mixed B", "Hildenborough C", "Walthamstow Hall School", "7.45"]);
data.push(["February", "Friday", "24th", "Mens A", "Trident C", "Angel Centre", "8"]);
data.push(["February", "Friday", "24th", "Mixed D", "Langton Green", "Langton Green Village Hall", "7.3"]);
data.push(["February", "Friday", "24th", "Ladies A", "St Johns B", "Angel Centre", "8"]);
data.push(["February", "Friday", "24th", "Edenbridge Comb", "Felbridge", "Angel Centre", "8"]);
data.push(["February", "Monday", "27th", "Masters", "Wadhurst B", "Wadhurst Village Hall", "7.3"]);
data.push(["February", "Monday", "27th", "Mixed A", "AIT B", "Mascalls", "8.15"]);
data.push(["March", "Wednesday", "1st", "Mixed B", "Trident E", "Angel Centre", "8"]);
data.push(["March", "Thursday", "2nd", "Mixed C", "Hildenborough E", "Walthamstow School Hall", "7.45"]);
data.push(["March", "Friday", "3rd", "Masters", "Sevenoaks", "Angel Centre", "8"]);
data.push(["March", "Friday", "3rd", "Mens C", "Hilden Grange", "Angel centre", "8"]);
data.push(["March", "Friday", "3rd", "Mixed A", "AIT B", "Angel Centre", "8"]);
data.push(["March", "Monday", "6th", "Ladies 4", "Trident", "Holmewood House School", "8"]);
data.push(["March", "Thursday", "9th", "Mens A", "Hildenborough C", "Walthamstow Hall School", "7.45"]);
data.push(["March", "Thursday", "9th", "Masters", "Wadhurst A", "Wadhurst Village Hall", "7.3"]);
data.push(["March", "Friday", "10th", "Ladies 4", "St Johns", "Angel Centre", "8"]);
data.push(["March", "Friday", "10th", "Mens B", "St Johns B", "Angel centre", "8"]);
data.push(["March", "Monday", "13th", "Mixed B", "Trident E", "Holmewood House School", "8"]);
data.push(["March", "Thursday", "16th", "Edenbridge Mens", "St Pauls", "St Paul’s Methodist Church", "8"]);
data.push(["March", "Friday", "17th", "Ladies 4", "Langton Green", "Langton Green Village Hall", "7.3"]);
data.push(["March", "Friday", "17th", "Mens C", "Langton Green", "Angel Centre", "8"]);
data.push(["March", "Friday", "17th", "Mens A", "St Johns A", "St Johns Sports Centre", "7.3"]);
data.push(["March", "Friday", "17th", "Mixed C", "St Johns C", "St Johns Sports Centre", "7.3"]);
data.push(["March", "Tuesday", "21st", "Mens B", "Sevenoaks B", "Sackville School", "8.15"]);
data.push(["March", "Wednesday", "22nd", "Edenbridge Comb", "Felbridge", "East Grinstead Sports centre", "7.3"]);
data.push(["March", "Thursday", "23rd", "Masters", "Hilden Grange", "Hilden Grange School", "8"]);
data.push(["March", "Friday", "24th", "Mixed A", "Hildenborough B", "Angel Centre", "8"]);
data.push(["March", "Friday", "24th", "Mixed C", "Sevenoaks B", "Angel Centre", "8"]);
data.push(["March", "Friday", "24th", "Edenbridge Mens", "Imberwood", "Brambletye School", "8.15"]);
data.push(["March", "Monday", "27th", "Mens C", "Sevenoaks C", "Sackville School", "8.15"]);
data.push(["March", "Monday", "27th", "Mixed A", "AIT A", "Mascalls School", "8.15"]);
data.push(["March", "Wednesday", "29th", "Ladies A", "Hildenborough B", "Angel Centre", "8"]);
data.push(["March", "Friday", "31st", "Mixed C", "Hilden Grange", "Angel Centre", "8"]);
data.push(["March", "Friday", "31st", "Edenbridge Mens", "St Piers", "St Piers Sports Hall", "8"]);
data.push(["April", "Tuesday", "4th", "Mens B", "Chelwood Gate", "Michael Hall School", "8"]);
data.push(["April", "Wednesday", "5th", "Edenbridge Comb", "St Piers", "Angel Centre", "8"]);
data.push(["April", "Thursday", "6th", "Mixed C", "Hilden Grange", "Hilden Grange School", "8"]);
data.push(["April", "Friday", "7th", "Ladies A", "St Johns A", "St Johns Sports Centre", "7.3"]);
data.push(["April", "Friday", "7th", "Edenbridge Mens", "Felbridge", "Angel Centre", "8"]);
data.push(["April", "Sunday", "9th", "Mixed C", "Trident F", "Holmewood House School", "8"]);
data.push(["April", "Thursday", "20th", "Mixed D", "Hilden Grange", "Hilden Grange School", "8"]);
data.push(["April", "Friday", "21st", "Edenbridge Comb", "St Piers", "St Piers Sports Hall", "8"]);
data.push(["April", "Friday", "21st", "Mens A", "AIT C", "Angel Centre", "8"]);
data.push(["April", "Friday", "21st", "Masters", "Hilden Grange", "Angel Centre", "8"]);
data.push(["April", "Sunday", "23rd", "Mixed B", "Trident D", "Holmewood House School", "8"]);
data.push(["April", "Tuesday", "25th", "Mixed D", "Sevenoaks C", "Sackville School", "8.15"]);
data.push(["April", "Wednesday", "26th", "Edenbridge Mens", "St Pauls", "Angel Centre", "8"]);
data.push(["April", "Friday", "28th", "Mixed B", "Hildenborough D", "Angel Centre", "8"]);
data.push(["April", "Friday", "28th", "Mixed D", "Langton Green", "Angel Centre", "8"]);
data.push(["April", "Sunday", "30th", "Masters", "Trident", "Holmewood House", "8"]);
data.push(["May", "Wednesday", "3rd", "Ladies 4", "AIT 4", "Angel Centre", "8"]);
data.push(["May", "Friday", "5th", "Masters", "Langton Green", "Angel Centre", "8"]);
data.push(["May", "Friday", "5th", "Mixed D", "Wadhurst", "Angel Centre", "8"]);
data.push(["May", "Wednesday", "10th", "Masters", "Trident", "Angel Centre", "8"]);
data.push(["May", "Friday", "12th", "Edenbridge Mens", "St Piers", "Angel Centre", "8"]);
