data.push(["Month", "Day", "Day of Month", "League", "Where", "Where", "Time"]);
data.push(["October", "Monday", "1st", "Masters", "Sevenoaks", "Weald of Kent Grammar School", "8"]);
data.push(["October", "Friday", "5th", "Mens C", "St johns E", "Angel Centre", "8"]);
data.push(["October", "Friday", "5th", "Ladies 4s", "Wadhurst", "Angel Centre", "8"]);
data.push(["October", "Friday", "5th", "Mens A", "AIT A", "Angel Centre", "8"]);
data.push(["October", "Sunday", "7th", "Mixed B", "Trident E", "Holmewood House School", "7"]);
data.push(["October", "Wednesday", "10th", "Mixed A", "AIT B", "Angel Centre", "8"]);
data.push(["October", "Friday", "12th", "Mixed B", "Hildenborough D", "Angel Centre", "8"]);
data.push(["October", "Monday", "15th", "Mens 4s", "Trident", "Holmewood House School", "8"]);
data.push(["October", "Wednesday", "17th", "Mixed C", "AIT C", "Angel Centre", "8"]);
data.push(["October", "Wednesday", "31st", "Mens C", "Sevenoaks C", "Angel Centre", "8"]);
data.push(["November", "Friday", "2nd", "Mixed A", "St Johns B", "Angel Centre", "8"]);
data.push(["November", "Friday", "2nd", "Mens C", "Hilden Grange", "Hilden Grange School", "8"]);
data.push(["November", "Monday", "5th", "Mixed A", "Sevenoaks A", "Weald of Kent Grammar School", "8"]);
data.push(["November", "Monday", "5th", "Mens C", "Sevenoaks C", "Weald of Kent Grammar School", "8"]);
data.push(["November", "Friday", "9th", "Mens B", "St johns C", "Angel Centre", "8"]);
data.push(["November", "Friday", "16th", "Mens 4s", "Hilden Grange", "Hilden Grange School", "8"]);
data.push(["November", "Friday", "16th", "Mens A", "Hildenborough A", "Walthamstow Hall", "8"]);
data.push(["November", "Friday", "16th", "Ladies 6s", "Hildenborough", "Walthamstow Hall", "8"]);
data.push(["November", "Friday", "16th", "Masters", "Langton Green", "The Village Hall", "7"]);
data.push(["November", "Thursday", "22nd", "Mixed A", "AIT B", "Mascalls Secondary School", "8"]);
data.push(["November", "Friday", "23rd", "Mixed B", "St Johns D", "Angel Centre", "8"]);
data.push(["November", "Friday", "23rd", "Mens 4s", "Hilden Grange", "Angel Centre", "8"]);
data.push(["November", "Monday", "26th", "Mixed A", "Trident C", "Holmewood House School", "8"]);
data.push(["November", "Wednesday", "28th", "Mens B", "Hildenborough D", "Angel Centre", "8"]);
data.push(["November", "Friday", "30th", "Mixed C", "St johns F", "Angel Centre", "8"]);
data.push(["November", "Friday", "30th", "Mixed A", "Hildenborough B", "Angel Centre", "8"]);
data.push(["November", "Friday", "30th", "Masters", "Hilden Grange", "Hilden Grange School", "8"]);
data.push(["December", "Sunday", "2nd", "Mens A", "chelwood gate", "Michael Hall School", "7"]);
data.push(["December", "Monday", "3rd", "Mens 4s", "AIT", "Mascalls Secondary School", "7"]);
data.push(["December", "Wednesday", "5th", "Mens B", "Sevenoaks B", "Angel Centre", "8"]);
data.push(["December", "Thursday", "6th", "Ladies 4s", "Wadhurst", "Commemoration Hall", "7"]);
data.push(["December", "Friday", "7th", "Ladies 4s", "Felbridge", "Angel Centre", "8"]);
data.push(["December", "Friday", "7th", "Mixed B", "St Johns E", "Angel Centre", "8"]);
data.push(["December", "Friday", "7th", "Mens C", "Langton Green", "The Village Hall", "7"]);
data.push(["December", "Wednesday", "12th", "Masters", "chelwood gate", "Angel Centre", "8"]);
data.push(["December", "Thursday", "13th", "Ladies 4s", "AIT", "Mascalls Secondary School", "8"]);
data.push(["December", "Friday", "14th", "Ladies 6s", "St johns C", "Angel Centre", "8"]);
data.push(["December", "Friday", "14th", "Mens B", "St johns D", "Angel Centre", "8"]);
data.push(["December", "Friday", "14th", "Mens 4s", "Paddock Wood B", "Angel Centre", "8"]);
data.push(["December", "Monday", "17th", "Ladies 6s", "Trident B", "Holmewood House School", "8"]);
data.push(["January", "Friday", "4th", "Mens B", "Hildenborough C", "Angel Centre", "8"]);
data.push(["January", "Tuesday", "8th", "Mixed C", "Langton Green", "The Village Hall", "7"]);
data.push(["January", "Friday", "11th", "Mixed A", "Hildenborough B", "Walthamstow Hall", "8"]);
data.push(["January", "Friday", "11th", "Mixed C", "Wadhurst", "Angel Centre", "8"]);
data.push(["January", "Friday", "11th", "Mens 4s", "Sevenoaks", "Angel Centre", "8"]);
data.push(["January", "Monday", "14th", "Mens B", "Sevenoaks B", "Weald of Kent Grammar School", "8"]);
data.push(["January", "Wednesday", "16th", "Ladies 6s", "Trident B", "Angel Centre", "8"]);
data.push(["January", "Friday", "18th", "Mixed A", "St Johns B", "Tunbridge Wells Sports Centre", "7"]);
data.push(["January", "Friday", "18th", "Mens 4s", "Wadhurst", "Angel Centre", "8"]);
data.push(["January", "Friday", "18th", "Ladies 4s", "Langton Green", "Angel Centre", "8"]);
data.push(["January", "Monday", "21st", "Mens 4s", "Mens 4s", "Putlands Sports & Leisure Centre", "8"]);
data.push(["January", "Wednesday", "23rd", "Ladies 6s", "Hildenborough", "Angel Centre", "8"]);
data.push(["January", "Friday", "25th", "Mixed B", "St Johns D", "Tunbridge Wells Sports Centre", "7"]);
data.push(["January", "Friday", "25th", "Ladies 4s", "AIT", "Angel Centre", "8"]);
data.push(["January", "Friday", "25th", "Mens 4s", "AIT", "Angel Centre", "8"]);
data.push(["January", "Monday", "28th", "Mens A", "AIT A", "Mascalls Secondary School", "7"]);
data.push(["January", "Monday", "28th", "Mens 4s", "Sevenoaks", "Weald of Kent Grammar School", "8"]);
data.push(["January", "Wednesday", "30th", "Mens A", "Chelwood Gate", "Angel Centre", "8"]);
data.push(["February", "Friday", "1st", "Mixed C", "St johns F", "Tunbridge Wells Sports Centre", "7"]);
data.push(["February", "Friday", "1st", "Masters", "Wadhurst A", "Angel Centre", "8"]);
data.push(["February", "Friday", "1st", "Mixed A", "Trident C", "Angel Centre", "8"]);
data.push(["February", "Thursday", "7th", "Mixed C", "Wadhurst", "Commemoration Hall", "7"]);
data.push(["February", "Friday", "8th", "Mixed B", "St Johns E", "Tunbridge Wells Sports Centre", "7"]);
data.push(["February", "Friday", "8th", "Ladies 4s", "Trident", "Angel Centre", "8"]);
data.push(["February", "Friday", "8th", "Mens 4s", "Trident", "Angel Centre", "8"]);
data.push(["February", "Monday", "11th", "Ladies 6s", "AIT", "Mascalls Secondary School", "7"]);
data.push(["February", "Monday", "11th", "Mens 4s", "Mens4s", "Putlands Sports & Leisure Centre", "8"]);
data.push(["February", "Friday", "15th", "Mens B", "St Johns C", "Tunbridge Wells Sports Centre", "7"]);
data.push(["February", "Sunday", "17th", "Mens A", "Trident B", "Holmewood House School", "8"]);
data.push(["February", "Sunday", "17th", "Masters", "Trident", "Holmewood House School", "8"]);
data.push(["February", "Monday", "25th", "Mens A", "Trident A", "Holmewood House School", "8"]);
data.push(["February", "Thursday", "28th", "Masters", "Wadhurst A", "Commemoration Hall", "7"]);
data.push(["March", "Friday", "1st", "Ladies 4s", "Langton Green", "The Village Hall", "7"]);
data.push(["March", "Wednesday", "6th", "Mens A", "Trident B", "Angel Centre", "8"]);
data.push(["March", "Friday", "8th", "Mens A", "Hildenborough B", "Angel Centre", "8"]);
data.push(["March", "Friday", "8th", "Mens C", "St Johns E", "Tunbridge Wells Sports Centre", "7"]);
data.push(["March", "Friday", "8th", "Masters", "Langton Green", "Angel Centre", "8"]);
data.push(["March", "Friday", "8th", "Ladies 6s", "AIT", "Angel Centre", "8"]);
data.push(["March", "Monday", "11th", "Ladies 4s", "Trident", "Holmewood House School", "8"]);
data.push(["March", "Wednesday", "13th", "Mixed C", "Langton Green", "Angel Centre", "8"]);
data.push(["March", "Thursday", "14th", "Mens 4s", "Wadhurst", "Commemoration Hall", "7"]);
data.push(["March", "Friday", "15th", "Ladies 6s", "St johns C", "Tunbridge Wells Sports Centre", "7"]);
data.push(["March", "Friday", "15th", "Mens B", "St Johns D", "Tunbridge Wells Sports Centre", "7"]);
data.push(["March", "Wednesday", "20th", "Mixed B", "Trident E", "Angel Centre", "8"]);
data.push(["March", "Friday", "22nd", "Mens A", "Hildenborough B", "Walthamstow Hall", "8"]);
data.push(["March", "Friday", "22nd", "Masters", "Wadhurst B", "Angel Centre", "8"]);
data.push(["March", "Friday", "22nd", "Mens C", "Hilden Grange", "Angel Centre", "8"]);
data.push(["March", "Wednesday", "27th", "Mens A", "Trident A", "Angel Centre", "8"]);
data.push(["March", "Friday", "29th", "Mens B", "Hildenborough C", "Walthamstow Hall", "8"]);
data.push(["April", "Wednesday", "3rd", "Ladies 4s", "Felbridge", "East Grinstead Sports Club", "7"]);
data.push(["April", "Thursday", "4th", "Masters", "Wadhurst B", "Commemoration Hall", "7"]);
data.push(["April", "Friday", "5th", "Mixed C", "Hilden Grange", "Angel Centre", "8"]);
data.push(["April", "Friday", "5th", "Mixed A", "Sevenoaks A", "Angel Centre", "8"]);
data.push(["April", "Friday", "12th", "Mixed B", "Hildenborough D", "Walthamstow Hall", "8"]);
data.push(["April", "Friday", "26th", "Mens A", "Hildenborough A", "Angel Centre", "8"]);
data.push(["April", "Friday", "26th", "Masters", "Hilden Grange", "Angel Centre", "8"]);
data.push(["April", "Friday", "26th", "Mens C", "Langton Green", "Angel Centre", "8"]);
data.push(["April", "Sunday", "28th", "Masters", "chelwood gate", "Michael Hall School", "7"]);
data.push(["May", "Wednesday", "1st", "Masters", "Trident", "Angel Centre", "8"]);
data.push(["May", "Friday", "3rd", "Mens B", "Hildenborough D", "Walthamstow Hall", "8"]);
data.push(["May", "Friday", "3rd", "Mixed C", "Langton Green", "The Village Hall", "7"]);
data.push(["May", "Wednesday", "8th", "Mens 4s", "Paddock Wood A", "Angel Centre", "8"]);
data.push(["May", "Friday", "10th", "Mixed C", "Hilden Grange", "Hugh Christie", "7"]);
data.push(["May", "Friday", "10th", "Masters", "Sevenoaks", "Angel Centre", "8"]);